import type { CatalogStats } from '@/utils/liveJobsPipeline'
import type { HeadlineStats } from '@/utils/headlineStats'

/** Snapshot-aligned totals — regenerated by scripts/sync-home-shell-stats.mjs after export/clean.
 *  `vacancies` / hero posts only count listings with vacancies > 0.
 */
export const HOME_SHELL_HEADLINE_STATS: HeadlineStats = {
  notifications: 19,
  vacancies: 163,
  orgs: 12,
}

/** Avoid importing full ORG_INDEX / OFFICIAL_SITES just for counts on the home shell. */
export const HOME_SHELL_ORG_COUNT = 12
export const HOME_SHELL_OFFICIAL_SOURCE_COUNT = 153

export const HOME_SHELL_CATALOG_STATS: CatalogStats = {
  totalNotices: 19,
  liveNotices: 19,
  vacancies: 163,
  noticesWithVacancies: 18,
}

export const HOME_SHELL_HERO_STATS = {
  posts: 163,
  withPostCount: 18,
  hotNew: 2,
  states: 8,
  stateListings: 16,
  live: 19,
}
