import type { CatalogStats } from '@/utils/liveJobsPipeline'
import type { HeadlineStats } from '@/utils/headlineStats'

/** Snapshot-aligned totals — regenerated by scripts/sync-home-shell-stats.mjs after export/clean.
 *  `vacancies` / hero posts only count listings with vacancies > 0.
 */
export const HOME_SHELL_HEADLINE_STATS: HeadlineStats = {
  notifications: 17,
  vacancies: 4622,
  orgs: 11,
}

/** Avoid importing full ORG_INDEX / OFFICIAL_SITES just for counts on the home shell. */
export const HOME_SHELL_ORG_COUNT = 11
export const HOME_SHELL_OFFICIAL_SOURCE_COUNT = 153

export const HOME_SHELL_CATALOG_STATS: CatalogStats = {
  totalNotices: 17,
  liveNotices: 17,
  vacancies: 4622,
  noticesWithVacancies: 17,
}

export const HOME_SHELL_HERO_STATS = {
  posts: 4622,
  withPostCount: 17,
  hotNew: 0,
  states: 6,
  stateListings: 14,
  live: 17,
}
