import type { CatalogStats } from '@/utils/liveJobsPipeline'
import type { HeadlineStats } from '@/utils/headlineStats'

/** Snapshot-aligned totals — regenerated by scripts/sync-home-shell-stats.mjs after export/clean. */
export const HOME_SHELL_HEADLINE_STATS: HeadlineStats = {
  notifications: 41,
  vacancies: 326,
  orgs: 19,
}

/** Avoid importing full ORG_INDEX / OFFICIAL_SITES just for counts on the home shell. */
export const HOME_SHELL_ORG_COUNT = 19
export const HOME_SHELL_OFFICIAL_SOURCE_COUNT = 153

export const HOME_SHELL_CATALOG_STATS: CatalogStats = {
  totalNotices: 41,
  liveNotices: 41,
  vacancies: 326,
  noticesWithVacancies: 27,
}

export const HOME_SHELL_HERO_STATS = {
  posts: 326,
  withPostCount: 27,
  hotNew: 7,
  states: 9,
  stateListings: 19,
  live: 41,
}
